import and call the env analysis script (#4)
* import the script

* list the dependencies

* call the script from within the action

* explicitly specify the shell

* quote the `envs-path` variable

* try setting the input type of env-paths

* try serializing to json

* quote the input

* missing shell

* correct the input name

* print the decoded paths

* typo

* use the right function names

* unquote

* try using `join`

* remove debug step

* allow expected failures

* add test env files

* compare strings instead

* pass expected failure as a list

* another failing example

* show the status of the current dir

* more debugging

* print the content of `envs`

* rename `env1`

* use a existing version of `pandas`

* use an existing version of `packaging`

* enforce a column width of 120

* proper syntax

* try setting in a different place

* remove debug step

* enforce colors

* remove the `always`

* split up into smaller steps

* don't cancel in-progress jobs when others fail

* cancel duplicate workflow runs

* continue if the action fails

* more output

* tests for `Spec.parse`

* always set the pass status

* check the output of the status functions

* consolidate into a single step

* continue on error

* some more adjustments

* fix the `xfail`

* Apply suggestions from code review

Co-authored-by: Mathias Hauser <mathause@users.noreply.github.com>

* expect pypi-compliant versions

* extend the inexact versions warning

* add and fix tests for `Policy.minimum_version`

---------

Co-authored-by: Mathias Hauser <mathause@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,11 +5,16 @@ on:
   pull_request:
     branches: [main]
 
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
+
 jobs:
   ci:
     name: tests
     runs-on: [ubuntu-latest]
     strategy:
+      fail-fast: false
       matrix:
         python-version: ["3.10", "3.11", "3.12", "3.13"]
 
@@ -36,16 +41,51 @@ jobs:
     runs-on: [ubuntu-latest]
 
     strategy:
+      fail-fast: false
       matrix:
         env-paths:
           - ["envs/env1.yaml"]
           - ["envs/env2.yaml"]
           - ["envs/env1.yaml", "envs/env2.yaml"]
+        expected-failure: ["false"]
+        include:
+          - env-paths: ["envs/failing-env1.yaml"]
+            expected-failure: "true"
+          - env-paths: ["envs/env1.yaml", "envs/failing-env1.yaml"]
+            expected-failure: "true"
 
     steps:
       - name: clone the repository
         uses: actions/checkout@v4
       - name: run action
         uses: ./
+        id: action-run
+        continue-on-error: true
         with:
-          environment-paths: ${{ matrix.env-paths }}
+          environment-paths: "${{ toJSON(matrix.env-paths) }}"
+      - name: detect outcome
+        if: always()
+        shell: bash -l {0}
+        run: |
+          if [[ "${{ steps.action-run.outcome }}" == "success" && ${{ matrix.expected-failure }} == "true" ]]; then
+              # unexpected pass
+              echo "workflow xpassed"
+              export STATUS=1
+          elif [[ "${{ steps.action-run.outcome }}" == "failure" && ${{ matrix.expected-failure }} == "false" ]]; then
+              # unexpected failure
+              echo "workflow failed"
+              export STATUS=2
+          elif [[ "${{ steps.action-run.outcome }}" == "success" && ${{ matrix.expected-failure }} == "false" ]]; then
+              # normal pass
+              echo "workflow passed"
+              export STATUS=0
+          elif [[ "${{ steps.action-run.outcome }}" == "failure" && ${{ matrix.expected-failure }} == "true" ]]; then
+              # expected failure
+              echo "workflow xfailed"
+              export STATUS=0
+          else
+              # cancelled
+              echo "workflow cancelled"
+              export STATUS=3
+          fi
+          exit $STATUS
